### ISSUE TITLE
Music always reshuffles when changing the music type

### ISSUE THREAD

**Issue by syahmiasyraff02** [relaxtakenotes/gm-action-music#10]
First of all, thanks for fixing the LUA error spam the addon made since the introduction of the smarter music reshuffle a couple of days ago. Now, I have another issue. As mentioned in my previous issue post, I have a problem that the addon will reshuffle the music twice in an interval of less than a second when changing the music type either dynamically or via force music type option. This happens regardless if the music isn't over yet and I tried messing around with both the song reshuffle period and the pack reshuffle period options in the settings, but they do nothing to alleviate the issue.

https://github.com/relaxtakenotes/gm-action-music/assets/147134106/8b09d247-1ae9-414c-8da7-63e18338a25a

**Comment by relaxtakenotes** [comment]
i like these nice detailed reports

you know the drill, try out the github version and tell me if it's behaving as expected

**Comment by relaxtakenotes** [comment]
i like these detailed reports

you know the drill, try out the latest github version and see if that works as expected

**Comment by syahmiasyraff02** [comment]
> i like these detailed reports
> 
> you know the drill, try out the latest github version and see if that works as expected

Kinda struggled to do that. Anyway, I'll check it out in a few hours.

**Comment by syahmiasyraff02** [comment]
Sorry for the long wait, but after testing the latest GitHub build I have some other issues:

1. While the latest build did fix the music reshuffling during dynamic or forced music type transition, the addon doesn't reshuffle to the next song (either from the same music pack if cl_am_reshuffle_pack_period command value is greater than 1 or from other music packs if the cl_am_reshuffle_pack_period command value is equal to 1) after the current song is finished. Using the cl_am_force_type command back and forth (e.g. from Background to Battle and vice versa) fixed the issue inconsistently and even then, the addon simply replays the same song instead of reshuffling to the other songs.
2. Speaking of the cl_am_force_type command, for example, whenever I switched the command value from 1 (Battle) to 0 (Default) while I have no enemy NPCs (which the addon typically plays the Ambient music type), the addon continued to play the Battle music until I spawned and kill an enemy NPCs, where the addon will switch back to the Ambient music. This applies to other command values as well.
3. You mentioned that by setting the cl_am_reshuffle_pack_period command value to 1, I will get the older reshuffling behavior. Right now, I can't seem to get it to work with the first issue still lingers around.

**Comment by relaxtakenotes** [comment]
didn't exactly rethink it all, but i for sure got rid of unnecessary complications.
so, i specifically fixed the first issue, second issue should've been fixed by itself during the little refactor i done, and third is unfortunately not exactly right. i failed to account for the fact that once you set it to 1, it's going to reshuffle the PACK every second and songs are still going to be picked from ONE PACK, however i believe the "smart" shuffle behavior is superior to the old one, so i wont be putting in effort into making the old one work in any way

**Comment by syahmiasyraff02** [comment]
> didn't exactly rethink it all, but i for sure got rid of unnecessary complications. so, i specifically fixed the first issue, second issue should've been fixed by itself during the little refactor i done, and third is unfortunately not exactly right. i failed to account for the fact that once you set it to 1, it's going to reshuffle the PACK every second and songs are still going to be picked from ONE PACK, however i believe the "smart" shuffle behavior is superior to the old one, so i wont be putting in effort into making the old one work in any way and yes, it's pushed to the repo

Well, that's a load of spaghetti over the last few days. For now, the issues I mentioned in this post is fixed.
