### ISSUE TITLE
Music just doesn't repeat

### ISSUE THREAD

**Issue by Badbadalex1** [relaxtakenotes/gm-action-music#11]
I've created my own Music pack and the tracks don't loop after they've ended, no errors appear in console or anything the music just stops and won't replay unless I reload the map..
As far as I can tell this doesn't happen with any other pack I've downloaded

**Comment by Badbadalex1** [comment]
https://github.com/relaxtakenotes/gm-action-music/assets/173845521/cdf252af-058b-4ae6-8e6f-4b2b60b6f1d3
Here's that video, pardon the low quality I had to make it fit on this website but it should still be readable
I couldn't find that debug command you mentioned although I have a feeling developer gives enough info still

**Comment by relaxtakenotes** [comment]
well doesn't seem to tell me much. can you send over the pack? you can use https://send.vis.ee/ for that

**Comment by Badbadalex1** [comment]
Sure here it is
https://send.vis.ee/download/d01bf7b8a199d7d5/#uledE0xLlVfq9jRyHTAAaQ

**Comment by Badbadalex1** [comment]
I didn't intend for it be a buildup and continuation it was just supposed to loop with one track in the category
but anyway so the issue is that I just needed more than one song in the categories?
