### ISSUE TITLE
Issue with songs continue playing even if I have disabled them in the configuration panel or set them via console.

### ISSUE THREAD

**Issue by Technomancer076** [relaxtakenotes/gm-action-music#12]
Songs wont stop playing even if i disable them in the config panel or console. even setting the all the volumes down to 0 doesnt work. 
Update: also happens even if i manually disable all the packs in the config menu
![20240702220036_1](https://github.com/relaxtakenotes/gm-action-music/assets/174571671/09cb9b8f-10ba-4f4f-9ca2-e962f763c74e)
![20240702220120_1](https://github.com/relaxtakenotes/gm-action-music/assets/174571671/8d811939-4e82-4e17-bb7b-2e738b3cf093)

**Comment by relaxtakenotes** [comment]
setting their volume to 0 wont work cause cl_am_enabled is supposed to do it. but in your case i suppose it's broken. mind recording this behaviour with developer 1?

**Comment by Technomancer076** [comment]
> setting their volume to 0 wont work cause cl_am_enabled is supposed to do it. but in your case i suppose it's broken. mind recording this behaviour with developer 1?

sure but how do i do that?

**Comment by relaxtakenotes** [comment]
open console, type "developer 1", press enter.
as for recording just google, it'll explain it way better than i can
