### ISSUE TITLE
LVS problems

### ISSUE THREAD

**Issue by hostkeks** [relaxtakenotes/gm-action-music#14]
if you're in the LVS vehicle and your AI team is enemy to other team, it will cause this error:
[Action Music (with pvp support)] lua/autorun/server/am_send_threat_events.lua:20: attempt to call method 'Disposition' (a nil value)
  1. targeted_teammate_is_near - lua/autorun/server/am_send_threat_events.lua:20
   2. unknown - lua/autorun/server/am_send_threat_events.lua:147
    3. unknown - lua/dlib/modules/hook.lua:904

**Comment by hostkeks** [comment]
if team is friendly to everyone, then this error will not appear

**Comment by relaxtakenotes** [comment]
pushed a fix to the workshop. go try it

**Comment by relaxtakenotes** [comment]
i reckon its fixed due to no answer and the fix generally being pretty obvious
