### ISSUE TITLE
Audio doesn't process

### ISSUE THREAD

**Issue by Lombaxtard** [relaxtakenotes/gm-action-music#2]
Audio never finishes processing, it just says "0 out of %" and never moves. There are less than two dozens tracks and I don't have that weak of a PC, but it's nowhere near the swiftness of your demonstration where it took you 1 minute off-screen to process audio.
![image](https://github.com/relaxtakenotes/gm-action-music/assets/75931669/04ec1486-565e-4c78-a3c3-463fb07ce575)
output.log is empty. Windows 10 with no compatibility settings, however I tried to run main.exe with Administrator privileges with no luck.
Tried to process one audio file without any special characters and even spaces to the same folder and still stuck for minutes at 0.

**Comment by wutwu2550** [comment]
same here

**Comment by relaxtakenotes** [comment]
Yeah I don't know why. That warrants writing the utility in a proper language and not python. Until then you gotta do all that shit manually  Friday, 26 May 2023, 02:05AM +05:00 from Lombaxtard  ***@***.*** :

**Comment by relaxtakenotes** [comment]
Hm. I might have fixed it. Try installing this ffmpeg build and then putting it into your global windows path (or just let the program do it for you once I push the fix. make sure it's not already installed in your system tho): https://github.com/BtbN/FFmpeg-Builds/releases/download/autobuild-2023-07-04-12-50/ffmpeg-N-111332-g9ff834c2a0-win64-lgpl-shared.zip

**Comment by relaxtakenotes** [comment]
I don't know if a change I made relates specifically to this, but I fixed something that should in theory fix this. Otherwise check your ffmpeg install. It might be installed wrong or you might need to install a shared/avcodec version.

**Comment by Lombaxtard** [comment]
> I don't know if a change I made relates specifically to this, but I fixed something that should in theory fix this. Otherwise check your ffmpeg install. It might be installed wrong or you might need to install a shared/avcodec version.

Can't test without binary, sorry

**Comment by relaxtakenotes** [comment]
> > I don't know if a change I made relates specifically to this, but I fixed something that should in theory fix this. Otherwise check your ffmpeg install. It might be installed wrong or you might need to install a shared/avcodec version.
> 
> Can't test without binary, sorry

I made a release.

**Comment by Lombaxtard** [comment]
> > > I don't know if a change I made relates specifically to this, but I fixed something that should in theory fix this. Otherwise check your ffmpeg install. It might be installed wrong or you might need to install a shared/avcodec version.
> > 
> > 
> > Can't test without binary, sorry
> 
> I made a release.

I tested your release with automatic ffmpeg install (not the link you provided) and tried it with one song (it couldn't handle even one so I figured that would be sufficient for a test) and it processed! For now, the issue is fixed for me, I suppose
Will have to revoke all of my doubts only after I make a complete Action Music (which is totally awesome too, by the way) pack with your tool. Cheers

**Comment by relaxtakenotes** [comment]
> > > > I don't know if a change I made relates specifically to this, but I fixed something that should in theory fix this. Otherwise check your ffmpeg install. It might be installed wrong or you might need to install a shared/avcodec version.
> > > 
> > > 
> > > Can't test without binary, sorry
> > 
> > 
> > I made a release.
> 
> I tested your release with automatic ffmpeg install (not the link you provided) and tried it with one song (it couldn't handle even one so I figured that would be sufficient for a test) and it processed! For now, the issue is fixed for me, I suppose Will have to revoke all of my doubts only after I make a complete Action Music (which is totally awesome too, by the way) pack with your tool. Cheers

Good to know! It was a really sneaky but simple bug too, which made it hard to find. Maybe switching the ffmpeg version made it better too.
