### ISSUE TITLE
Bugs related to Music Trigger and Force Music Type

### ISSUE THREAD

**Issue by syahmiasyraff02** [relaxtakenotes/gm-action-music#6]
As stated in the title, I have a couple of issues regarding both the Music Trigger and the Force Music Type from the mod.

1. Music Trigger

- The trigger for both the battle and intense battle music only applies to human NPCs (e.g. citizens, rebels, combine soldiers, civil protection units etc.).
- Other NPCs such as zombies, antlions and non-human combine units and equipment do not trigger both the battle and intense battle music.
- This forces me to use the force music type every time I got engaged into combat with non-human NPCs.

2. Force Music Type

- For some reason, both the battle and intense battle music do not automatically reshuffle to the next song as soon as the previous one ends when using the force music type command.
- To fix this, I have to use the cl_am_initialize_song command to force reshuffle the music every time a battle or intense battle song has ended.
- Strangely, this issue does not apply to background music when using force music type.

I hope these bugs get fixed in the future because they're bothersome.

**Comment by syahmiasyraff02** [comment]
Oh I see. Seemed like I forgot that command existed to fix the issue no. 1 altogether, my bad. However, I think I have to reiterate what I said on the second point on the issue no. 2. What I meant there is that I have to use the cl_am_initialize_song to ensure the smooth transition into the next song when using music force type for both the battle and intensive battle music.

**Comment by relaxtakenotes** [comment]
tried fixing the non combatant mode. you can get the newest version from this repo and try it out yourself before i push it to workshop.
didnt really understand your shuffle issue nor did i experience anything wrong with it from my testing.

**Comment by syahmiasyraff02** [comment]
Tried the latest version you upload here and by setting the sv_am_ignore_noncombatans to 0 as you mentioned, the issue no. 1 has been fixed. For the second issue though, I have to provide a video evidence for you. Hope this is convincing enough...

https://github.com/relaxtakenotes/gm-action-music/assets/147134106/66dee984-3697-4d35-957d-690545787a78

**Comment by relaxtakenotes** [comment]
send me the pack you were using in that video

**Comment by syahmiasyraff02** [comment]
Nombat - COD MW2 - https://steamcommunity.com/sharedfiles/filedetails/?id=924083928
Nombat - MW2019 - https://steamcommunity.com/sharedfiles/filedetails/?id=2734424464
Nombat - Modern Warfare II - https://steamcommunity.com/sharedfiles/filedetails/?id=2893948362

Wait a sec. You said that you didn't have that second issue. Does this have to do with using Nombat music?

**Comment by relaxtakenotes** [comment]
maybe. but i still need to see what exactly causes it because i want proper support for other music packs

**Comment by relaxtakenotes** [comment]
i found a bug that MAY have caused this, but funnily enough i still couldn't replicate it. will push a fix to the repo soon, then you can try it out for yourself before i push it to the workshop

**Comment by syahmiasyraff02** [comment]
I just tried out the latest version you uploaded on the repo, and both issues are thankfully fixed.

**Comment by syahmiasyraff02** [comment]
I just tried out the latest version you uploaded on the repo, and both issues are thankfully fixed.
