### ISSUE TITLE
Issue - FFmpeg not working

### ISSUE THREAD

**Issue by archive94-412shoes** [relaxtakenotes/gm-action-music#8]
I'm not sure what version, build, or from what site you got your FFmpeg, but it isn't working for me.

I put in the FFmpeg 6.1 version. Didn't work. I took the one that was linked under the Windows download page, and put it next to the .exe. Didn't work. I put it in tools, library, and even above the application. Every single time didn't work. 

Could you link your FFmpeg or whatever you have going on?

**Comment by relaxtakenotes** [comment]
forgot this issue existed, however it is fixed both in the python build and the c++ build
